export const memberInfo = [
    {
        id: 1,
        photo: '',
        name: 'Александр Тимошенко',
        role: 'Team Lead',
        linkedIn: '',
        gitHub: '',
        telegram: '',
    },
    {
        id: 2,
        photo: '',
        name: 'Марк Неловка',
        role: 'Scrum Master',
        linkedIn: 'https://www.linkedin.com/in/mark-nelovka/',
        gitHub: 'https://github.com/Mark-Nelovka',
        telegram: '@MarkNelovka',
    },
    {
        id: 3,
        photo: '',
        name: 'Евгения Малахова',
        role: 'Developer',
        linkedIn: '',
        gitHub: '',
        telegram: '',
    },
    {
        id: 4,
        photo: '',
        name: 'Дмитрий Малик',
        role: 'Developer',
        linkedIn: '',
        gitHub: 'https://github.com/salat4',
        telegram: '@Stalt4',
    },
    {
        id: 5,
        photo: '',
        name: 'Александр Бодачевский',
        role: 'Developer',
        linkedIn: '',
        gitHub: '',
        telegram: '',
    },
    {
        id: 6,
        photo: '',
        name: 'Артем Акулов',
        role: 'Developer',
        linkedIn: 'https://www.linkedin.com/in/artem-akulov-b264aa1b1/',
        gitHub: 'https://github.com/artyomakulov',
        telegram: '@artyomakulov',
    },
    {
        id: 7,
        photo: '',
        name: 'Игорь Гладкий',
        role: 'Developer',
        linkedIn: 'https://www.linkedin.com/in/igor-gladkiy-530b211b3/',
        gitHub: 'https://github.com/chetkiy777',
        telegram: '@Igorek_Chetkiy',
    },
    {
        id: 8,
        photo: '',
        name: 'Андрей Березовский',
        role: 'Developer',
        linkedIn: 'https://www.linkedin.com/in/andriy-berezovskyi/',
        gitHub: 'https://github.com/AndriyBerezovskyi',
        telegram: '@dyus95',
    },
];