export const memberInfo = [
    {
        id: 'C1',
        photo: 'https://raw.githubusercontent.com/OleksandrTymoshenko/js-project-10/main/src/partials/img/members/malakhova.jpg',
        name: 'Yevheniia Malakhova',
        role: 'Developer',
        linkedIn: 'https://www.linkedin.com/in/yevheniia-malakhova',
        gitHub: 'https://github.com/jennmala',
        telegram: 'https://t.me/jennmala',
    },
    {
        id: 'C2',
        photo: 'https://raw.githubusercontent.com/OleksandrTymoshenko/js-project-10/main/src/partials/img/members/malik.jpg',
        name: 'Dmytro Malik',
        role: 'Developer',
        linkedIn: 'https://www.linkedin.com/in/%D0%B4%D0%B8%D0%BC%D0%B0-%D0%BC%D0%B0%D0%BB%D0%B8%D0%BA-5550a022a/',
        gitHub: 'https://github.com/salat4',
        telegram: 'https://t.me/Stalt4',
    },
    {
        id: 'C3',
        photo: 'https://raw.githubusercontent.com/OleksandrTymoshenko/js-project-10/main/src/partials/img/members/berezovskyi.jpg',
        name: 'Andriy Berezovskyi',
        role: 'Developer',
        linkedIn: 'https://www.linkedin.com/in/andriy-berezovskyi/',
        gitHub: 'https://github.com/AndriyBerezovskyi',
        telegram: 'https://t.me/dyus95',
    },
    {
        id: 'C4',
        photo: 'https://raw.githubusercontent.com/OleksandrTymoshenko/js-project-10/main/src/partials/img/members/akulov.jpg',
        name: 'Artem Akulov',
        role: 'Developer',
        linkedIn: 'https://www.linkedin.com/in/artem-akulov-b264aa1b1/',
        gitHub: 'https://github.com/artyomakulov',
        telegram: 'https://t.me/artyomakulov',
    },
    {
        id: 'C5',
        photo: 'https://raw.githubusercontent.com/OleksandrTymoshenko/js-project-10/main/src/partials/img/members/bodachevskyi.jpg',
        name: 'Oleksandr Bodachevskyi',
        role: 'Developer',
        linkedIn: '',
        gitHub: 'https://github.com/AlexBodach',
        telegram: 'https://t.me/BodachevskyOl',
    },
    {
        id: 'C6',
        photo: 'https://raw.githubusercontent.com/OleksandrTymoshenko/js-project-10/main/src/partials/img/members/gladkyi.jpg',
        name: 'Igor Gladkyi',
        role: 'Developer',
        linkedIn: 'https://www.linkedin.com/in/igor-gladkiy-530b211b3/',
        gitHub: 'https://github.com/chetkiy777',
        telegram: 'https://t.me/Igorek_Chetkiy',
    },
    {
        id: 'C7',
        photo: 'https://raw.githubusercontent.com/OleksandrTymoshenko/js-project-10/main/src/partials/img/members/nelovka.jpg',
        name: 'Mark Nelovka',
        role: 'Scrum Master',
        linkedIn: 'https://www.linkedin.com/in/mark-nelovka/',
        gitHub: 'https://github.com/Mark-Nelovka',
        telegram: 'https://t.me/MarkNelovka',
    },
    {
        id: 'C8',
        photo: 'https://raw.githubusercontent.com/OleksandrTymoshenko/js-project-10/main/src/partials/img/members/tymoshenko.jpg',
        name: 'Oleksandr Tymoshenko',
        role: 'Team Lead',
        linkedIn: 'https://www.linkedin.com/in/александр-тимошенко-75994941',
        gitHub: 'https://github.com/OleksandrTymoshenko',
        telegram: 'https://t.me/AlxTxlA',
    },
];